name: Feature Branch Tests

on:
  push:
    branches: [ 'feature/*' ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Check test coverage
      run: npm run test:coverage
      
    - name: Comment test results on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Read test results
          let testResults = '✅ All tests passed!';
          let coverageResults = '';
          
          try {
            const coveragePath = path.join(process.cwd(), 'coverage', 'lcov-report', 'index.html');
            if (fs.existsSync(coveragePath)) {
              coverageResults = '\n📊 Coverage report generated successfully.';
            }
          } catch (error) {
            console.log('Coverage report not found');
          }
          
          const comment = `## 🧪 Test Results
          
          ${testResults}${coverageResults}
          
          **Branch:** \`${context.payload.pull_request.head.ref}\`
          **Commit:** \`${context.payload.pull_request.head.sha.substring(0, 7)}\`
          
          <details>
          <summary>View detailed results</summary>
          
          Check the [Actions tab](https://github.com/${context.repo.owner}/${context.repo.repo}/actions) for full test logs.
          </details>`;
          
          github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

